In [92]:
import pandas as pd
import numpy as np

In [93]:
df = pd.read_csv(r"C:\Users\Karthik2025\OneDrive\Desktop\NAVITHA\Project 3\insurance_business_intelligence_dirty_raw_10000x15.csv")

In [3]:
print(df.shape)

(10000, 15)

In [4]:
print(df.head())

  Customer_ID  Policy_ID Customer_Name   Age        City Policy_Type  \
0  CUST104935  POL204935   Rahul Patel  36.0        Pune        Auto
1  CUST105976  POL205976   Rahul Patel  59.0  Coimbatore        Auto
2  CUST103293  POL203293   Anjali Iyer  23.0     Chennai     Annuity
3  CUST108676  POL208676  Priya Sharma  68.0       Delhi        Auto
4  CUST109973  POL209973   Rahul Patel  52.0       Delhi   Term Life

  Policy_Start_Date Policy_Status  Annual_Premium  Sum_Assured Claim_Status  \
0        2023-08-14        Active        75049.22   1297675.45      Pending
1        2022-08-15     Cancelled        96076.43   1317404.84     Approved
2        2021-11-09        Lapsed        67613.78    255026.68       Denied
3        2021-11-08        Lapsed        54219.15    183263.36      Pending
4        2021-01-04       Expired        83103.15    386815.13     Approved

   Claim_Amount  Deductible Sales_Channel   Payment_Mode
0     150800.78     6384.26        Online     Auto Debit
1      98012.01     2677.88        Broker     Auto Debit
2     187783.33     4502.93       Partner  Bank Transfer
3      97514.24     4841.59        Branch     Auto Debit
4     375656.24     6091.45        Broker     Debit Card

In [5]:
df.describe()

               Age  Annual_Premium   Sum_Assured  Claim_Amount   Deductible
count  9965.000000    9.972000e+03  9.976000e+03  9.970000e+03  9980.000000
mean     46.342699    5.421040e+04  1.267253e+06  2.022431e+05  5197.184787
std      16.894431    5.664091e+04  7.190222e+05  1.509525e+05  2776.095987
min       0.000000   -9.632341e+04 -2.396812e+06 -3.648140e+05 -9942.250000
25%      32.000000    2.914927e+04  6.428731e+05  1.003462e+05  2797.650000
50%      46.000000    5.281478e+04  1.270855e+06  1.997601e+05  5176.255000
75%      61.000000    7.656794e+04  1.888204e+06  3.019605e+05  7588.897500
max     120.000000    1.985803e+06  2.499735e+06  4.926147e+06  9999.430000

In [6]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        9982 non-null   str
 1   Policy_ID          9988 non-null   str
 2   Customer_Name      9980 non-null   str
 3   Age                9965 non-null   float64
 4   City               9978 non-null   str
 5   Policy_Type        9982 non-null   str
 6   Policy_Start_Date  9975 non-null   str
 7   Policy_Status      9980 non-null   str
 8   Annual_Premium     9972 non-null   float64
 9   Sum_Assured        9976 non-null   float64
 10  Claim_Status       9979 non-null   str
 11  Claim_Amount       9970 non-null   float64
 12  Deductible         9980 non-null   float64
 13  Sales_Channel      9982 non-null   str
 14  Payment_Mode       9980 non-null   str
dtypes: float64(5), str(10)
memory usage: 1.1 MB
None

In [7]:
df[df["Policy_ID"].duplicated(keep = False)]

,Customer_ID,Policy_ID,Customer_Name,Age,City,Policy_Type,Policy_Start_Date,Policy_Status,Annual_Premium,Sum_Assured,Claim_Status,Claim_Amount,Deductible,Sales_Channel,Payment_Mode
76,CUST101991,POL201991,Suresh Verma,19.0,Kolkata,Annuity,2022-07-06,Active,84243.38,1329168.94,No Claim,373416.10,7785.24,Partner,Auto Debit
191,CUST101285,POL201285,Priya Sharma,38.0,Chennai,Term Life,2022-08-09,Cancelled,52215.66,2020199.29,Under Review,115781.08,4888.87,Online,Bank Transfer
253,CUST106531,POL206531,Karthik Reddy,20.0,Ahmedabad,Annuity,2022-07-29,Cancelled,30446.63,2393509.84,Denied,68025.75,1582.36,Broker,Credit Card
288,CUST104231,POL204231,Vijay Nair,69.0,Jaipur,Annuity,2024-12-19,Expired,73070.89,941326.60,Under Review,281882.87,780.30,Online,UPI
390,CUST102668,POL202668,Priya Sharma,19.0,Delhi,Health,2023-03-27,Cancelled,56060.22,1936991.48,Approved,164886.16,3184.27,Branch,Bank Transfer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9494,CUST106147,NaN,Suresh Verma,48.0,Pune,Auto,2023-11-17,Cancelled,45668.50,1794058.83,Approved,258253.76,1266.91,Broker,UPI
9589,CUST101672,POL206189,Vijay Nair,67.0,Delhi,Term Life,2023-11-21,Cancelled,31949.50,924534.88,Pending,95141.02,844.58,Branch,Cash
9674,CUST104799,POL204799,Suresh Verma,60.0,Bengaluru,Home,2023-08-26,Cancelled,64892.46,1888144.39,Pending,170019.25,6113.76,Online,Credit Card
9736,CUST105731,POL205731,Vijay Nair,59.0,Coimbatore,Term Life,2022-08-26,Lapsed,37977.27,402147.24,Pending,356982.22,4471.68,Agent,Auto Debit
9749,CUST108666,POL208666,Divya Gupta,29.0,Ahmedabad,Home,2025-08-17,Lapsed,20779.08,100093.49,Denied,66831.42,655.18,Broker,Credit Card

In [70]:
df = df.drop_duplicates()

In [8]:
df.isnull().sum()

Customer_ID          18
Policy_ID            12
Customer_Name        20
Age                  35
City                 22
Policy_Type          18
Policy_Start_Date    25
Policy_Status        20
Annual_Premium       28
Sum_Assured          24
Claim_Status         21
Claim_Amount         30
Deductible           20
Sales_Channel        18
Payment_Mode         20
dtype: int64

In [9]:
missing_percentage = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

print(missing_percentage)

Age                  0.35
Claim_Amount         0.30
Annual_Premium       0.28
Policy_Start_Date    0.25
Sum_Assured          0.24
City                 0.22
Claim_Status         0.21
Policy_Status        0.20
Deductible           0.20
Payment_Mode         0.20
Customer_Name        0.20
Customer_ID          0.18
Policy_Type          0.18
Sales_Channel        0.18
Policy_ID            0.12
dtype: float64

In [10]:
duplicate_policies = df[df["Policy_ID"].duplicated(keep=False)]
print(duplicate_policies)

     Customer_ID  Policy_ID  Customer_Name   Age        City Policy_Type  \
76    CUST101991  POL201991   Suresh Verma  19.0     Kolkata     Annuity
191   CUST101285  POL201285   Priya Sharma  38.0     Chennai   Term Life
253   CUST106531  POL206531  Karthik Reddy  20.0   Ahmedabad     Annuity
288   CUST104231  POL204231     Vijay Nair  69.0      Jaipur     Annuity
390   CUST102668  POL202668   Priya Sharma  19.0       Delhi      Health
...          ...        ...            ...   ...         ...         ...
9494  CUST106147        NaN   Suresh Verma  48.0        Pune        Auto
9589  CUST101672  POL206189     Vijay Nair  67.0       Delhi   Term Life
9674  CUST104799  POL204799   Suresh Verma  60.0   Bengaluru        Home
9736  CUST105731  POL205731     Vijay Nair  59.0  Coimbatore   Term Life
9749  CUST108666  POL208666    Divya Gupta  29.0   Ahmedabad        Home

     Policy_Start_Date Policy_Status  Annual_Premium  Sum_Assured  \
76          2022-07-06        Active        84243.38   1329168.94
191         2022-08-09     Cancelled        52215.66   2020199.29
253         2022-07-29     Cancelled        30446.63   2393509.84
288         2024-12-19       Expired        73070.89    941326.60
390         2023-03-27     Cancelled        56060.22   1936991.48
...                ...           ...             ...          ...
9494        2023-11-17     Cancelled        45668.50   1794058.83
9589        2023-11-21     Cancelled        31949.50    924534.88
9674        2023-08-26     Cancelled        64892.46   1888144.39
9736        2022-08-26        Lapsed        37977.27    402147.24
9749        2025-08-17        Lapsed        20779.08    100093.49

      Claim_Status  Claim_Amount  Deductible Sales_Channel   Payment_Mode
76        No Claim     373416.10     7785.24       Partner     Auto Debit
191   Under Review     115781.08     4888.87        Online  Bank Transfer
253         Denied      68025.75     1582.36        Broker    Credit Card
288   Under Review     281882.87      780.30        Online            UPI
390       Approved     164886.16     3184.27        Branch  Bank Transfer
...            ...           ...         ...           ...            ...
9494      Approved     258253.76     1266.91        Broker            UPI
9589       Pending      95141.02      844.58        Branch           Cash
9674       Pending     170019.25     6113.76        Online    Credit Card
9736       Pending     356982.22     4471.68         Agent     Auto Debit
9749        Denied      66831.42      655.18        Broker    Credit Card

[118 rows x 15 columns]

In [11]:
print(df["Policy_ID"].duplicated().sum())

64

In [12]:
df.dtypes

Customer_ID              str
Policy_ID                str
Customer_Name            str
Age                  float64
City                     str
Policy_Type              str
Policy_Start_Date        str
Policy_Status            str
Annual_Premium       float64
Sum_Assured          float64
Claim_Status             str
Claim_Amount         float64
Deductible           float64
Sales_Channel            str
Payment_Mode             str
dtype: object

In [13]:
text_columns = [
    "Customer_ID",
    "Policy_ID",
    "Customer_Name",
    "City",
    "Policy_Type",
    "Policy_Status",
    "Claim_Status",
    "Sales_Channel",
    "Payment_Mode"
]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

In [14]:
df["Customer_Name"] = df["Customer_Name"].str.title()

In [15]:
df["City"]= df["City"].str.title()

In [16]:
df["Policy_Type"]=df["Policy_Type"].str.title()

In [17]:
df["Policy_Status"]=df["Policy_Status"].str.title()

In [18]:
df["Claim_Status"]=df["Claim_Status"].str.title()

In [19]:
df["City"].unique()

<StringArray>
[      'Pune', 'Coimbatore',    'Chennai',      'Delhi',         <NA>,
  'Ahmedabad',    'Kolkata',  'Bengaluru',     'Jaipur',     'Mumbai',
  'Hyderabad',  'Bangalore',   'Hyderbad']
Length: 13, dtype: string

In [20]:
df["City"] = df["City"].replace({
    "chennai": "Chennai",
    "Bengaluru": "Bangalore",
    "Hyderbad": "Hyderabad"
})

In [21]:
df["City"].unique()

<StringArray>
[      'Pune', 'Coimbatore',    'Chennai',      'Delhi',         <NA>,
  'Ahmedabad',    'Kolkata',  'Bangalore',     'Jaipur',     'Mumbai',
  'Hyderabad']
Length: 11, dtype: string

In [22]:
print(df["City"].value_counts())

City
Bangalore     1074
Hyderabad     1034
Pune          1025
Chennai       1017
Kolkata       1012
Ahmedabad      976
Jaipur         972
Mumbai         972
Coimbatore     969
Delhi          927
Name: count, dtype: Int64

In [23]:
df["Policy_Type"].unique()

<StringArray>
[     'Auto',   'Annuity', 'Term Life',    'Health',    'Travel',      'Home',
      'Life', 'Term-Life',        <NA>]
Length: 9, dtype: string

In [24]:
df["Policy_Type"]=df["Policy_Type"].replace({"Term_Life" : "Term Life"})

In [25]:
print(df["Policy_Type"].value_counts())

Policy_Type
Health       1486
Annuity      1466
Travel       1452
Home         1434
Auto         1396
Term Life    1387
Life         1353
Term-Life       8
Name: count, dtype: Int64

In [26]:
df["Sales_Channel"].unique()

<StringArray>
['Online', 'Broker', 'Partner', 'Branch', 'Agent', 'ON-LINE', <NA>, 'online']
Length: 8, dtype: string

In [27]:
df["Sales_Channel"] = df["Sales_Channel"].replace({"online":"Online","ON-LINE":"Online"})

In [28]:
print(df["Sales_Channel"].value_counts())

Sales_Channel
Branch     2065
Online     2028
Partner    1971
Broker     1963
Agent      1955
Name: count, dtype: Int64

In [29]:
df["Payment_Mode"].unique()

<StringArray>
[   'Auto Debit', 'Bank Transfer',    'Debit Card',   'Credit Card',
          'Cash',           'UPI',    'CreditCard',           'upi',
            <NA>]
Length: 9, dtype: string

In [30]:
df["Payment_Mode"]=df["Payment_Mode"].replace({"CreditCard":"Credit Card","upi":"UPI"})

In [31]:
print(df["Age"].describe())

count    9965.000000
mean       46.342699
std        16.894431
min         0.000000
25%        32.000000
50%        46.000000
75%        61.000000
max       120.000000
Name: Age, dtype: float64

In [32]:
invalid_age = df[
    (df["Age"] < 18) | (df["Age"] > 100)
]

print("Invalid ages:", len(invalid_age))

Invalid ages: 30

In [33]:
df["Age"]=df["Age"].fillna(df["Age"].median())

In [34]:
df["Age"]=df["Age"].astype(int)

In [64]:
df["Policy_Start_Date"] = pd.to_datetime(
    df["Policy_Start_Date"],
    errors="coerce"
)

In [65]:
print(
    df["Policy_Start_Date"].isnull().sum()
)

40

In [63]:
missing_dates = df[
    df["Policy_Start_Date"].isnull()
]

print(missing_dates[[
    "Customer_ID",
    "Policy_ID",
    "Policy_Start_Date"
]])

     Customer_ID  Policy_ID Policy_Start_Date
452   CUST100971  POL200971               NaT
575   CUST101330  POL201330               NaT
656   CUST103136  POL203136               NaT
886   CUST105470  POL205470               NaT
952   CUST102437  POL202437               NaT
966   CUST106537  POL206537               NaT
1077  CUST108394  POL208394               NaT
1686  CUST109390  POL209390               NaT
1912  CUST104009  POL204009               NaT
1939  CUST109228  POL209228               NaT
2242  CUST100701  POL200701               NaT
2771  CUST109115  POL209115               NaT
2796  CUST102768  POL202768               NaT
3339  CUST101838  POL201838               NaT
3355  CUST108534  POL208534               NaT
3490  CUST106543  POL206543               NaT
3832  CUST107429  POL207429               NaT
3950  CUST101132  POL201132               NaT
4736  CUST102428  POL202428               NaT
5710  CUST109397  POL209397               NaT
5714  CUST104711  POL204711               NaT
5842  CUST103785  POL203785               NaT
6135  CUST101207  POL201207               NaT
6283  CUST100276  POL200276               NaT
6629  CUST103279  POL203279               NaT
6879  CUST101026  POL201026               NaT
6939  CUST104143  POL204143               NaT
7327  CUST106856  POL206856               NaT
7365  CUST106089  POL206089               NaT
7758  CUST100320  POL200320               NaT
7800  CUST108645  POL208645               NaT
7888  CUST101075  POL201075               NaT
8456  CUST108933  POL208933               NaT
8637  CUST103016  POL203016               NaT
8866  CUST100739  POL200739               NaT
9354  CUST106222  POL206222               NaT
9402  CUST105953  POL205953               NaT
9446  CUST100053  POL200053               NaT
9681  CUST103234  POL203234               NaT
9797  CUST108912  POL208912               NaT

In [66]:
df["Policy_Start_Date"] = df["Policy_Start_Date"].fillna(
    df["Policy_Start_Date"].median()
)

In [67]:
print(
    df["Policy_Start_Date"].isnull().sum()
)

0

In [37]:
financial_columns = [
    "Annual_Premium",
    "Sum_Assured",
    "Claim_Amount",
    "Deductible"
]

for col in financial_columns:
    print(col)
    print(df[col].describe())

Annual_Premium
count    9.972000e+03
mean     5.421040e+04
std      5.664091e+04
min     -9.632341e+04
25%      2.914927e+04
50%      5.281478e+04
75%      7.656794e+04
max      1.985803e+06
Name: Annual_Premium, dtype: float64
Sum_Assured
count    9.976000e+03
mean     1.267253e+06
std      7.190222e+05
min     -2.396812e+06
25%      6.428731e+05
50%      1.270855e+06
75%      1.888204e+06
max      2.499735e+06
Name: Sum_Assured, dtype: float64
Claim_Amount
count    9.970000e+03
mean     2.022431e+05
std      1.509525e+05
min     -3.648140e+05
25%      1.003462e+05
50%      1.997601e+05
75%      3.019605e+05
max      4.926147e+06
Name: Claim_Amount, dtype: float64
Deductible
count    9980.000000
mean     5197.184787
std      2776.095987
min     -9942.250000
25%      2797.650000
50%      5176.255000
75%      7588.897500
max      9999.430000
Name: Deductible, dtype: float64

In [38]:
for col in financial_columns:
    print(
        col,
        (df[col] < 0).sum()
    )

Annual_Premium 18
Sum_Assured 18
Claim_Amount 18
Deductible 18

In [39]:
for col in financial_columns:
    df.loc[df[col] < 0, col] = np.nan

In [40]:
for col in financial_columns:
    print(
        col,
        "Negative:", 
        (df[col] < 0).sum()
    )

Annual_Premium Negative: 0
Sum_Assured Negative: 0
Claim_Amount Negative: 0
Deductible Negative: 0

In [41]:
df["Annual_Premium"] = df["Annual_Premium"].fillna(
    df["Annual_Premium"].median()
)

In [42]:
df["Sum_Assured"] = df["Sum_Assured"].fillna(
    df["Sum_Assured"].median()
)

In [43]:
df["Deductible"] = df["Deductible"].fillna(
    df["Deductible"].median()
)

In [44]:
df.loc[
    df["Claim_Status"] == "No Claim",
    "Claim_Amount"
] = 0

In [45]:
df["Claim_Amount"] = df["Claim_Amount"].fillna(0)

In [46]:
problem_claims = df[
    (df["Claim_Status"] == "No Claim") &
    (df["Claim_Amount"] > 0)
]

print(problem_claims)

Empty DataFrame
Columns: [Customer_ID, Policy_ID, Customer_Name, Age, City, Policy_Type, Policy_Start_Date, Policy_Status, Annual_Premium, Sum_Assured, Claim_Status, Claim_Amount, Deductible, Sales_Channel, Payment_Mode]
Index: []

In [47]:
df.loc[
    df["Claim_Status"] == "No Claim",
    "Claim_Amount"
] = 0

In [48]:
approved_zero = df[
    (df["Claim_Status"] == "Approved") &
    (df["Claim_Amount"] == 0)
]

print(approved_zero)

     Customer_ID  Policy_ID  Customer_Name  Age        City Policy_Type  \
327   CUST107891  POL207891    Divya Gupta   39        Pune   Term Life
692   CUST106263  POL206263  Karthik Reddy   50     Chennai   Term Life
788   CUST109021  POL209021     Arun Kumar   23      Jaipur        Life
1596  CUST100731  POL200731    Sneha Singh   49   Ahmedabad        Auto
1698  CUST103853  POL203853      Meena Rao   25   Hyderabad        Life
2199  CUST101164  POL201164    Rahul Patel   51      Jaipur   Term Life
2730  CUST103370  POL203370    Anjali Iyer   55        Pune     Annuity
3993  CUST109311  POL209311    Divya Gupta   24   Bangalore      Travel
4191  CUST101724  POL201724  Karthik Reddy   23   Bangalore     Annuity
4502  CUST106638  POL206638   Suresh Verma   18   Ahmedabad      Health
4646  CUST105454  POL205454    Anjali Iyer   26     Kolkata      Travel
5349  CUST108794  POL208794     Arun Kumar   19     Kolkata   Term Life
5565  CUST103424  POL203424     Arun Kumar   18      Mumbai      Health
6776  CUST107358  POL207358   Suresh Verma   23  Coimbatore      Travel
6965  CUST100065  POL200065    Rahul Patel   36   Bangalore     Annuity
7215  CUST104020  POL204020  Karthik Reddy   29     Chennai   Term Life
7794  CUST107879  POL207879   Priya Sharma   18   Hyderabad      Travel
7938  CUST101862  POL201862    Rahul Patel   46       Delhi        Life
8201  CUST105173  POL205173     Arun Kumar   55        Pune        Auto
8396  CUST109965  POL209965   Suresh Verma   56  Coimbatore        Home
9097  CUST103313  POL203313      Meena Rao   26   Ahmedabad        Home
9513  CUST104079  POL204079      Meena Rao   28     Chennai        Auto
9823  CUST107145  POL207145     Arun Kumar   49      Jaipur        Life

     Policy_Start_Date Policy_Status  Annual_Premium  Sum_Assured  \
327         2022-07-31        Active        80409.79    142579.15
692         2022-06-06        Lapsed        67900.76   2415882.83
788         2024-04-02       Expired        38982.20    414982.19
1596        2022-05-19        Lapsed        15958.14   2216300.61
1698        2025-12-27     Cancelled        48912.51    402485.55
2199        2021-06-02     Cancelled        78972.33   1340882.13
2730        2023-03-01        Lapsed        48894.46   1284265.28
3993        2022-01-31        Lapsed        28873.79   2476083.77
4191        2025-10-27        Lapsed        10777.75    802611.58
4502        2025-03-26     Cancelled        72339.99   1030458.30
4646        2021-01-29        Lapsed         7298.58   2211782.26
5349        2024-03-14       Expired        64476.91   1946159.48
5565        2022-12-30     Cancelled        74336.68   2153232.89
6776        2022-08-07     Cancelled        58496.88   1157911.97
6965        2023-07-12     Cancelled        54800.31   1864693.96
7215        2021-11-08       Expired        52736.17   1680434.23
7794        2025-12-27     Cancelled        52370.09    977774.50
7938        2021-07-18       Expired        93749.59    588512.92
8201        2022-07-01     Cancelled        57781.35   2230122.87
8396        2024-02-16        Active        75291.92   1381139.00
9097        2024-12-18        Active        38174.26   1116368.81
9513        2021-03-14     Cancelled         5861.57   1859178.83
9823        2022-12-22     Cancelled        76887.75   1666562.40

     Claim_Status  Claim_Amount  Deductible Sales_Channel   Payment_Mode
327      Approved           0.0     4382.01       Partner            UPI
692      Approved           0.0     9797.23         Agent    Credit Card
788      Approved           0.0      998.95         Agent    Credit Card
1596     Approved           0.0     6220.44         Agent    Credit Card
1698     Approved           0.0     4486.12       Partner            UPI
2199     Approved           0.0     6317.04        Broker  Bank Transfer
2730     Approved           0.0     6595.22        Broker    Credit Card
3993     Approved           0.0     9325.02        Branch            UPI
4191     Approved           0.0     6150.92        Online  Bank Transfer
4502     Approved           0.0     1177.95         Agent           Cash
4646     Approved           0.0     5671.53        Branch     Auto Debit
5349     Approved           0.0     3481.05        Broker            UPI
5565     Approved           0.0     7613.47         Agent  Bank Transfer
6776     Approved           0.0     4035.96        Online     Debit Card
6965     Approved           0.0     1126.78         Agent    Credit Card
7215     Approved           0.0      905.98       Partner  Bank Transfer
7794     Approved           0.0     2030.57       Partner            UPI
7938     Approved           0.0     7957.13         Agent     Auto Debit
8201     Approved           0.0     5342.01         Agent     Debit Card
8396     Approved           0.0     1413.19        Branch            UPI
9097     Approved           0.0     2413.25       Partner           Cash
9513     Approved           0.0     4656.90        Branch     Auto Debit
9823     Approved           0.0     2236.77        Branch           Cash

In [49]:
problem_claim = df[(df["Claim_Status"]=="No Claim")&(df["Claim_Amount"]>0)]
print(problem_claim)

Empty DataFrame
Columns: [Customer_ID, Policy_ID, Customer_Name, Age, City, Policy_Type, Policy_Start_Date, Policy_Status, Annual_Premium, Sum_Assured, Claim_Status, Claim_Amount, Deductible, Sales_Channel, Payment_Mode]
Index: []

In [50]:
df.loc[df["Claim_Status"]=="No Claim","Claim_Amount"]=0

In [51]:
categorical_columns = [
    "City",
    "Policy_Type",
    "Policy_Status",
    "Claim_Status",
    "Sales_Channel",
    "Payment_Mode"
]

for col in categorical_columns:
    df[col] = df[col].fillna(
        df[col].mode()[0]
    )

In [52]:
Q1 = df["Annual_Premium"].quantile(0.25)
Q3 = df["Annual_Premium"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Annual_Premium"] < lower_limit) |
    (df["Annual_Premium"] > upper_limit)
]

print("Premium outliers:", len(outliers))

Premium outliers: 12

In [53]:
df["Premium_Outlier_Flag"] = np.where(
    (df["Annual_Premium"] < lower_limit) |
    (df["Annual_Premium"] > upper_limit),
    "Yes",
    "No"
)

In [54]:
df["Claim_Ratio"] = np.where(
    df["Annual_Premium"] > 0,
    df["Claim_Amount"] / df["Annual_Premium"],
    0
)

In [88]:
age_mapping = {
    "18-25": 1,
    "26-35": 2,
    "36-45": 3,
    "46-55": 4,
    "56-65": 5,
    "65+": 6
}

df["Age_Group_Code"] = df["Age_Group"].map(age_mapping)

In [89]:
print(df[["Age_Group", "Age_Group_Code"]].head(10))

  Age_Group Age_Group_Code
0     36-45              3
1     56-65              5
2     18-25              1
3       65+              6
4     46-55              4
5     36-45              3
6     26-35              2
7     46-55              4
8       65+              6
9     26-35              2

In [91]:
df["Age_Group_Code"] = df["Age_Group_Code"].astype(int)

ValueError: Cannot convert float NaN to integer

In [85]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[17, 25, 35, 45, 55, 65, 100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "65+"
    ]
)

In [56]:
df["Premium_Band"] = pd.cut(
    df["Annual_Premium"],
    bins=[0, 10000, 25000, 50000, 100000, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High",
        "Premium"
    ]
)

In [57]:
print(df.shape)

(10000, 19)

In [86]:
print(df.isnull().sum())

Customer_ID             18
Policy_ID               12
Customer_Name           20
Age                      0
City                     0
Policy_Type              0
Policy_Start_Date        0
Policy_Status            0
Annual_Premium           0
Sum_Assured              0
Claim_Status             0
Claim_Amount             0
Deductible               0
Sales_Channel            0
Payment_Mode             0
Premium_Outlier_Flag     0
Claim_Ratio              0
Age_Group               30
Premium_Band             0
Age_Group_Code          30
dtype: int64

In [71]:
print("Duplicates:",df.duplicated().sum())

Duplicates: 0

In [90]:
print(df.dtypes)

Customer_ID                     string
Policy_ID                       string
Customer_Name                   string
Age                              int64
City                            string
Policy_Type                     string
Policy_Start_Date       datetime64[us]
Policy_Status                   string
Annual_Premium                 float64
Sum_Assured                    float64
Claim_Status                    string
Claim_Amount                   float64
Deductible                     float64
Sales_Channel                   string
Payment_Mode                    string
Premium_Outlier_Flag               str
Claim_Ratio                    float64
Age_Group                     category
Premium_Band                  category
Age_Group_Code                category
dtype: object